repos:
  - repo: local
    hooks:
      - id: terraform-fmt-contabo
        name: terraform fmt contabo
        language: system
        entry: bash -c 'cd modules/contabo && terraform fmt'
        pass_filenames: false

      - id: terraform-validate-contabo
        name: terraform validate contabo
        language: system
        entry: bash -c 'cd modules/contabo && terraform validate'
        pass_filenames: false

      - id: terraform-docs-contabo
        name: terraform-docs contabo
        language: system
        entry: bash -c 'cd modules/contabo && terraform-docs md table .'
        pass_filenames: false

      - id: terraform-fmt-digitalocean
        name: terraform fmt digitalocean
        language: system
        entry: bash -c 'cd modules/digitalocean && terraform fmt'
        pass_filenames: false

      - id: terraform-validate-digitalocean
        name: terraform validate digitalocean
        language: system
        entry: bash -c 'cd modules/digitalocean && terraform validate'
        pass_filenames: false

      - id: terraform-docs-digitalocean
        name: terraform-docs digitalocean
        language: system
        entry: bash -c 'cd modules/digitalocean && terraform-docs md table .'
        pass_filenames: false

      - id: terraform-fmt-hetzner
        name: terraform fmt hetzner
        language: system
        entry: bash -c 'cd modules/hetzner && terraform fmt'
        pass_filenames: false

      - id: terraform-validate-hetzner
        name: terraform validate hetzner
        language: system
        entry: bash -c 'cd modules/hetzner && terraform validate'
        pass_filenames: false

      - id: terraform-docs-hetzner
        name: terraform-docs hetzner
        language: system
        entry: bash -c 'cd modules/hetzner && terraform-docs md table .'
        pass_filenames: false

      - id: terraform-fmt-vsphere
        name: terraform fmt vsphere
        language: system
        entry: bash -c 'cd modules/vsphere && terraform fmt'
        pass_filenames: false

      - id: terraform-validate-vsphere
        name: terraform validate vsphere
        language: system
        entry: bash -c 'cd modules/vsphere && terraform validate'
        pass_filenames: false

      - id: terraform-docs-vsphere
        name: terraform-docs vsphere
        language: system
        entry: bash -c 'cd modules/vsphere && terraform-docs md table .'
        pass_filenames: false

